name: Deploy Go App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build the application
      run: |
        export CGO_ENABLED=0
        go build -ldflags="-extldflags=-static" -o app main.go

    - name: Add EC2 Host to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      env:
          AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
      run: |
          echo "${AWS_PRIVATE_KEY}" > private_key.pem
          chmod 600 private_key.pem   
          ssh -o StrictHostKeyChecking=no -i private_key.pem ec2-user@$EC2_HOST << 'EOF'
          pkill app || true 
          EOF
          scp -o StrictHostKeyChecking=no -i private_key.pem app ec2-user@$EC2_HOST:/home/ec2-user/app
          ssh -o StrictHostKeyChecking=no -i private_key.pem ec2-user@$EC2_HOST << 'EOF'
          nohup /home/ec2-user/app > app.log 2>&1 &  
          EOF
