name: Deploy Go App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20

    - name: Build Go application
      run: go build -o app main.go

    - name: Deploy to EC2
      env:
        AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
        EC2_USER: ubuntu
        EC2_HOST: <EC2_INSTANCE_IP>
      run: |
        echo "${AWS_PRIVATE_KEY}" > private_key.pem
        chmod 600 private_key.pem
        scp -o StrictHostKeyChecking=no -i private_key.pem app $EC2_USER@$EC2_HOST:/home/ubuntu/app
        ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST << 'EOF'
        pkill app || true
        nohup /home/ubuntu/app > /home/ubuntu/app.log 2>&1 &
        EOF
