name: Deploy Go App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install build tools
      run: sudo apt-get install -y build-essential gcc

    - name: Build the application
      run: |
        export CGO_ENABLED=0
        go build -ldflags="-extldflags=-static" -o app main.go

    - name: Deploy to EC2
      env:
        AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
      run: |
        echo "${AWS_PRIVATE_KEY}" > private_key.pem
        chmod 600 private_key.pem
        scp -i private_key.pem app ubuntu@$EC2_HOST:/home/ubuntu/app
        ssh -i private_key.pem ubuntu@$EC2_HOST 'pkill app || true && nohup /home/ubuntu/app > app.log 2>&1 &'
